openapi: 3.1.0
info:
  version: 2.0.0
  title: Nordic Smart Government and Business API 
  termsOfService: https://example.com/terms/
  contact:
    email: contact@example.com
    url: http://example.com/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: logo.svg
  description:
    $ref: ./description.md
servers:
  - url: https://example.org/nsgb
security:
  - main_auth:
      - orgname:read
tags:
  - name: nordicinformation
    description: API to retrieve data about legal entities.
  - name: isalive
    description: API to control the status of the service.
paths:
  /v2/is-alive:
    $ref: paths/isalive.yaml
  /v2/legal-entities:
    $ref: paths/legalentity.yaml
  /id/{identifier}:
    $ref: paths/id/identifier.yaml
  /id/{identifier}/signatory-rights:
    $ref: paths/id/signatoryrights.yaml
  /v2/financial-statements:
    $ref: paths/financialstatements.yaml
components:
  securitySchemes:
    main_auth:
      $ref: components/securitySchemes/main_auth.yaml
    api_key:
      $ref: components/securitySchemes/api_key.yaml
    basic_auth:
      $ref: components/securitySchemes/basic_auth.yaml

